/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.queixal.cdi.beans;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import javax.enterprise.inject.Instance;
import javax.inject.Inject;

import org.jboss.weld.junit5.EnableWeld;
import org.jboss.weld.junit5.WeldInitiator;
import org.jboss.weld.junit5.WeldSetup;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.api.TestMethodOrder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@EnableWeld
@TestMethodOrder(OrderAnnotation.class)
@TestInstance(Lifecycle.PER_CLASS)
class CDIPlaygroundTest {
    
    private static final Logger log = LoggerFactory.getLogger(CDIPlaygroundTest.class);

	@WeldSetup
	public WeldInitiator weld = WeldInitiator.of(WeldInitiator.createWeld().disableIsolation().enableDiscovery()
			.addPackages(true, Feline.class));

    @Inject
    @FelineType("cat")
    private Feline cat;

    @Inject
    @FelineType("panther")
    private Feline panther;

    @Inject
    private Instance<Feline> feline;

    @Inject
    private Feline amiguousFeline;

    @Inject
    private ProducerConfig config;

    /**
     * Testing producers with qualifiers and amiguous definition using a factory pattern
     */
    @Test void testProducerFactory() {
        assertNotNull(amiguousFeline);
        config.setTypeToUse("cat");
        assertTrue(feline.get() instanceof Cat);
        config.setTypeToUse("panther");
        assertTrue(feline.get() instanceof Panther);
        //check Injected methods
        assertTrue(cat instanceof Cat);
        assertTrue(panther instanceof Panther);
    }
}
